"""Add description field to Product

Revision ID: 6ba28bc7cd37
Revises: 88e860890ee4
Create Date: 2025-03-31 11:43:45.409044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba28bc7cd37'
down_revision = '88e860890ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint('suppliers_email_key', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('suppliers_email_key', ['email'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
