"""Add description, stock, and accreditation to products

Revision ID: b550a51392d9
Revises: 6ba28bc7cd37
Create Date: 2025-03-31 11:50:28.064498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b550a51392d9'
down_revision = '6ba28bc7cd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accreditation', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('accreditation')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
